#!/usr/bin/env python3
"""
Converts classified_items.json into assets/latest-data.js, the file
latest.html actually reads in the browser.

Keeps the newest N items only, so the data file doesn't grow forever.
"""
import json
from datetime import datetime, timezone
from email.utils import parsedate_to_datetime
from pathlib import Path

HERE = Path(__file__).parent
SITE_DATA_PATH = HERE.parent / "assets" / "latest-data.js"
MAX_ITEMS = 60


def guess_iso_date(raw: str) -> str:
    """Best-effort conversion of whatever date format a feed gave us.
    Tries ISO format first (YouTube-style), then RFC822 (RSS-style, which
    handles named timezones like GMT/BST correctly -- unlike strptime's
    %z, which only understands numeric offsets like +0000)."""
    if not raw:
        return datetime.now(timezone.utc).isoformat()
    try:
        return datetime.fromisoformat(raw).astimezone(timezone.utc).isoformat()
    except (ValueError, TypeError):
        pass
    try:
        dt = parsedate_to_datetime(raw)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt.astimezone(timezone.utc).isoformat()
    except (ValueError, TypeError):
        pass
    return datetime.now(timezone.utc).isoformat()


def main():
    classified_path = HERE / "classified_items.json"
    items = json.loads(classified_path.read_text())

    out_items = []
    for i, item in enumerate(items):
        out_items.append({
            "id": f"item-{i}-{abs(hash(item['url'])) % 100000}",
            "title": item["title"],
            "source": item["source"],
            "category": item["category"],
            "published": guess_iso_date(item.get("published_raw", "")),
            "url": item["url"],
            "type": item.get("type", "article"),
        })

    out_items.sort(key=lambda x: x["published"], reverse=True)
    out_items = out_items[:MAX_ITEMS]

    js_content = (
        "// Auto-generated by automation/update_site_data.py -- do not edit by hand.\n"
        f"// Last updated: {datetime.now(timezone.utc).isoformat()}\n"
        "const LATEST_ITEMS = " + json.dumps(out_items, indent=2, ensure_ascii=False) + ";\n"
    )

    SITE_DATA_PATH.write_text(js_content, encoding="utf-8")
    print(f"Wrote {len(out_items)} items -> {SITE_DATA_PATH}")


if __name__ == "__main__":
    main()
